version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003:2003"
  discovery:
    build: ./platform-services/discovery
    ports:
      - "8761:8761"
  apigateway:
    build: ./platform-services/apigateway
    ports:
      - "8089:8089"
    links:
      - discovery
  one:
    build: ./business-services/one
    ports:
      - "8086:8086"
    links:
      - apigateway
      - zipkin
      - graphite
      - discovery
  two:
    build: ./business-services/two
    ports:
      - "8088:8088"
    links:
      - one
      - zipkin
      - graphite
      - discovery