server:
  port: 8089
spring:
  application:
    name: apigateway
zuul:
  routes:
    products:
      url: http://localhost:8089/
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
