server:
  port: 8088
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: two